# This file is created to contain options of categorial factors for ML price predicting models.
producers = ['Abarth', 'Acura', 'Adler', 'Alfa Romeo', 'Anaig', 'Aro', 'Artega', 'Asia', 'Aston Martin', 'Audi', 'Austin', 'BMW', 'BYD', 'Barkas (Баркас)', 'Bentley', 'Brilliance', 'Buick', 'Cadillac', 'Chana', 'Changhe', 'Chery', 'Chevrolet', 'Chrysler', 'Citroen', 'DAF / VDL', 'Dacia', 'Dadi', 'Daewoo', 'Daihatsu', 'Dodge', 'Dongfeng', 'Eagle', 'FAW', 'FSO', 'FUQI', 'Ferrari', 'Fiat', 'Fiat-Abarth', 'Fisker', 'Ford', 'GMC', 'Geely', 'Geo', 'Gonow', 'Great Wall', 'Groz', 'Hafei', 'Hanomag', 'Haval', 'Honda', 'Hong Xing', 'Huabei', 'Huanghai', 'Humber', 'Hummer', 'Hyundai', 'Infiniti', 'Innocenti', 'Iran Khodro', 'Isuzu', 'ItalCar', 'Iveco', 'JAC', 'Jaguar', 'Jeep', 'Jinbei', 'Jonway', 'Kia', 'LDV', 'Lada', 'Lamborghini', 'Lancia', 'Land Rover', 'Landwind', 'Lexus', 'Lifan', 'Lincoln', 'Lotus', 'MG', 'MINI', 'MPM Motors', 'Maserati', 'Maybach', 'Mazda', 'McLaren', 'Mercedes-Benz', 'Mercury', 'Mitsubishi', 'Morgan', 'Nissan', 'Nysa (Ныса)', 'Oldsmobile', 'Opel', 'Peugeot', 'Plymouth', 'Pontiac', 'Porsche', 'Proton', 'Ram', 'Ravon', 'Renault', 'Renault Samsung Motors', 'Rezvani', 'Rolls-Royce', 'Rover', 'SEAT', 'SMA', 'Saab', 'Saipa', 'Samand', 'Samsung', 'Saturn', 'Scion', 'Shuanghuan', 'Skoda', 'Smart', 'SouEast', 'SsangYong', 'Subaru', 'Suzuki', 'Tesla', 'Tianma', 'Toyota', 'Trabant', 'Volkswagen', 'Volvo', 'Wanderer', 'Wanfeng', 'Wartburg', 'Willys', 'Wuling', 'Xin kai', 'ZX', 'Zastava', 'Zotye', 'Zuk', 'Богдан', 'ВАЗ', 'ВИС', 'ГАЗ', 'Другое', 'ЕРАЗ', 'ЗАЗ', 'ЗИМ', 'ИЖ', 'ЛуАЗ', 'Москвич / АЗЛК', 'РАФ', 'Ретро автомобили', 'СМЗ', 'Самодельный', 'СеАЗ', 'УАЗ']
models = open('models.txt','r')
models = models.readlines()
models = [model[:-1] for model in models]
fuels = ['benzin','dizel','gaz-benzin','gaz','gibrid','elektro','gaz-metan','gaz-propan-butan','drugoe']
transmissions = ['Автомат', 'Ручная / Механика', 'Типтроник', 'Вариатор', 'Адаптивная']
powertrains = ['Полный', 'Передний', 'Задний']
bodies = ['Внедорожник / Кроссовер', 'Универсал', 'Минивэн', 'Седан', 'Лифтбек', 'Легковой фургон (до 1,5 т)', 'Хэтчбек', 'Купе', 'Пикап', 'Кабриолет', 'Лимузин', 'Родстер']
regions = ['poltava','kharkov','ivano-frankovsk','khmelnickij','dnepr-dnepropetrovsk','kiev','lvov','luczk','vinnica','odessa','ternopol','chernovczy','uzhgorod','cherkassy','chernigov','zaporozhe','zhitomir','kherson','nikolaev','doneck','lugansk','rovno','sumy','respublika-krym','kropivnickij-kirovograd']
conditions = ['Гаражное хранение', 'Индивидуальная комплектация', 'Не бит', 'Не крашен', 'Первый владелец', 'Пригоню под заказ', 'Ручное управление для инвалидов', 'Сервисная книжка', 'Требует ремонта']
safeties = ['ABD', 'ABS', 'ESP', 'Бронированный автомобиль', 'Галогенные фары', 'Замок на КПП', 'Иммобилайзер', 'Пневмоподвеска', 'Подушка безопасности (Airbag)', 'Серворуль', 'Сигнализация', 'Центральный замок']
comforts = ['Бортовой компьютер', 'Датчик света', 'Запуск кнопкой', 'Климат контроль', 'Кожаный салон', 'Кондиционер', 'Круиз контроль', 'Люк', 'Мультируль', 'Омыватель фар', 'Память сидений', 'Парктроник', 'Подогрев зеркал', 'Подогрев руля', 'Подогрев сидений', 'Сенсор дождя', 'Усилитель руля', 'Эл. стеклоподъемники', 'Электропакет']
multimedias = ['CD', 'DVD', 'MP3', 'Акустика', 'Магнитола', 'Сабвуфер', 'Система навигации GPS']
others = ['Газовая установка  (ГБО)', 'Дерево', 'Длинная база', 'Кузов MAXI', 'Правый руль', 'Тонирование стекол', 'Тюнинг', 'Фаркоп']
tags = ['Не на ходу', 'Первая регистрация', 'После ДТП', 'Пригнан']